config/routes.rb
ElasticoExample::Application.routes.draw do
  get "static_pages/readme"

  get "apples/index"

  root :to => 'static_pages#readme'

end

app/models/apple.rb
class Apple < ActiveRecord::Base

  attr_accessible :color, :name

	def self.prepare_elastico_settings_and_mappings_json
	  json = { "settings" => 
	  					{
	  						"number_of_shards" => 3
	  					},
	  					"mappings" =>
	  					{
	  							"apple" => 
	  							{
	  								"properties" => 
	  								{
											"name" => {"type" => "string"},
									    "color" => {"type" => "string"}
									  }
	  							}
	  					}
						}.to_json
  end

  # include elastico only after you declared your settings and mappings json in the method prepare_elastico_settings_and_mappings_json
  include Elastico
  Apple.elastico_url = "http://vokdxbxi:dhkxpsqfg8fy2bnr@banyan-6062486.us-east-1.bonsai.io:9200/" if Rails.env == "production"
  send_settings_mappings_to_elasticsearch_server

end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
  def index
  	if params[:query]
  		Apple.search_query = prepare_search_json_for params[:query]
  		@apples = Apple.elastico_search
  	else
  		@apples = Apple.all
  	end
  end

  private
	  def prepare_search_json_for query
	  	json = { "query" => 
					  		{
					        "term" => { "color" => query.to_s }
					    	}
					  	}.to_json
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def readme
  end
end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/apples/_apple.html.erb
<div class="row">
	<div class="span4">
		<%= apple.name %>
	</div>
	<div class="span4">
		<%= apple.color %>
	</div>
</div>

app/views/apples/_search_form.html.erb
<%= form_tag("index", method: "get") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/apples/index.html.erb
<h1>Apples index with elasticsearch</h1>
<%= link_to 'View all', apples_index_path %>
<%= link_to 'Readme', static_pages_readme_path %>
<%= render 'search_form' %>
<% if params[:query] %>
<h3>For the query:</h3>
<p>
	<%= Apple.search_query %>
</p>
<p>(try to change the query to "_all" instead of "color" and start searching for names as well)</p>
<h3>Elastico search will return this: </h3>
<% end %>
<%= @apples.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElasticoExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<a href="https://github.com/gneyal/ElasticoExample" target="blank"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
<%= yield %>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44980151-1', 'elasticoexample.herokuapp.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/static_pages/readme.html.erb
<h1>Elastico Example App</h1>
<h3>Hi there! This app demonstrates how to use the elastico gem</h3>

<p>
	It's quiet simple. We have an apple model, which has a name and color and we want to be able to search it.
</p>

<h3>If you cloned/forked the app</h3>
<ul>
	<li>Install and Run elasticsearch by following <%= link_to 'this link', 'http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup.html#setup-installation', :target => "_blank" %>.</li>
	<li>Run rake db:migrate</li>
	<li>Run rake db:seed</li>
	<li>Play with rails c while creating and deleting Apples. Watch how elasticsearch is updated automatically when you create or delete an instance. You can view elasticsearch indices by installing the <%= link_to 'head',"http://mobz.github.io/elasticsearch-head/", :target => "_blank" %>  plugin. </li>
	<li>Hop on to <%= link_to 'the apples index page', apples_index_path %> and play with the search.</li>
	<li>Note that the initial query only searches for colors. It will not find names. Change it to include names searching by changing the search query to "_all" instead of "color" in the apples controller. </li>
</ul>
<h3>If you are viewing the app online</h3>
<ul>
	<li>Hop on to <%= link_to 'the apples index page', apples_index_path %> and play with the search.</li>
	<li>Note that the initial query only searches for colors. It will not find names. You can change the query (and the mapping, getting ngram search available in no-time) it if you clone/fork the app, and view it locally.  </li>
</ul>